add_newline = true
right_format = """$directory"""

[character]
success_symbol = "[>](bold magenta)[>](bold cyan)[>](bold green)" 
error_symbol   = "[](bold red)"

[username]
style_user = "white bold"
style_root = "white bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "[@](bold blue)[$hostname](bold cyan) "
trim_at = ""
disabled = false

[cmd_duration]
disabled = true

[directory]
home_symbol = "~"
format = "[$path]($style) "

[time]
disabled = true

[git_branch]
symbol = " "
style = "bold blue"

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold cyan"
conflicted = "= "
ahead = "⇡ ${count} "
behind = "⇣ ${count} "
diverged = "⇕ "
up_to_date = ""
untracked = "? "
stashed = "$ "
modified = "! "
staged = '[++\($count\)](green)'
renamed = "» "
deleted = " "