add_newline = true
right_format = """$directory"""

[character]
success_symbol = "[](bold black)[](bold blue)[](bold white)" 
error_symbol   = "[]](bold red)"

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
ssh_only = false
format =  "@[$hostname](bold blue) "
trim_at = ""
disabled = false

[cmd_duration]
disabled = true

[directory]
format = "[ ](bold cyan)[$path]($style) "

[time]
disabled = true